# Use root/example as user/password credentials
version: '3.8'

services:
  loadbalancer:
    container_name: nginxloadbalancer
    image: nginx:stable-alpine3.17-slim
    networks:
      - loadbalancernetwork
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: ./nginx/nodejs-basic.conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - nodebackend
  nodebackend:
    container_name: nodebackend
    image: pedrohenriquegarcia/nodebackend
    entrypoint: dockerize -wait tcp://mysqldatabase:3306 -timeout 20s node src/app.js
    build: ./node
    networks:
      - backendnetwork
      - loadbalancernetwork
    depends_on:
      - mysqldb
  mysqldb:
    container_name: mysqldatabase
    image: mysql:8.3.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: testemysql
      MYSQL_DATABASE: NodeDatabase
    networks:
      - backendnetwork
    volumes:
      - type: bind
        source: ./mysql/
        target: /docker-entrypoint-initdb.d/

networks:
  backendnetwork:
    driver: bridge
  loadbalancernetwork:
    driver: bridge

