# Use root/example as user/password credentials
version: '3.8'

services:
  db:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testemysql
      MYSQL_DATABASE: nodedatabase
    networks:
      - backendnetwork
    volumes:
      - type: bind
        source: ./mysql/
        target: /docker-entrypoint-initdb.d/

networks:
  backendnetwork:
    driver: bridge
  loadbalancernetwork:
    driver: bridge

